Update readme to point to the SDK docs
NebulousLabs/skynet-js pull request #55
Opened 2020-08-06 16:28 UTC by m-cat

2020-08-19 13:40 UTC, kwypchlo requested changes
Add examples to `open` `getDownloadUrl` and `parseSkylink`.

Also, it's weird to me that some functions are documented here and some in the api docs - I think all of them should be moved to API docs.

2020-08-19 17:14 UTC, m-cat commented
> Also, it's weird to me that some functions are documented here and some in the api docs - I think all of them should be moved to API docs.

Yeah, I think so, too. I don't know yet how I'll do it without adding bloat for the other SDKs, which don't have these features.

2020-08-19 17:37 UTC, m-cat commented
Okay, added them to the SDK docs. Raised https://github.com/NebulousLabs/skynet-docs/pull/26

2020-08-20 09:46 UTC, kwypchlo approved these changes

2020-08-20 11:35 UTC, merged